// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irhugynyefkdyzmyrwap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyaHVneW55ZWZrZHl6bXlyd2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMzk0NjcsImV4cCI6MjA1NzYxNTQ2N30.nIXWyWAoxi4T9pKJ0_3s6Xy1gypL8GYVQmtKJtnDG-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);